dist: xenial      # this sets the Ubuntu distribution and is ignored on macOS or Windows
language: python  # this works for Linux but is an error on macOS or Windows
os: linux


# Set OCTOPUS_* environment variables used for testing
env:
  global:
    - secure: "OIgFwRazCKB16mQpIk2uHUzFSAq/lMoYt9uZMxQsd4SIlOeklk/80vupVlLdYwqdLdHWyPGIfBqvl6GPuTvYJPlJyUPf5bs/qA8qk7ImUdMlrrChD6mpmUG11suY1VZ1BmJT0hAtPHUk6xrcEK/1sTc/13R1AonnHwNxdQ3i59YWK2IU9ib9pe0KdOeHfSb6EMd7/n9ICf4Z5b/MxgL0nn/TfwFOXcPlfusD+TH5S2VxVUH6bmf8EiJhdip4tN1HaXji72eA4tSmvNCNhwYhRvTEG8JYTtT3Es1OkwXId9DHS9d6eGYRHAVPYX1tTNtVNoO94TRywz0gTJxiPVKY9ttlbvPRUZh6d3dOzRIxaIk9q/cHmmzxoiJFn3suh+23f4qa9nSXsts3rAdTy+MXWGKvFVfg4dp3HG/7W70KRblzYs7zozKNCtngOwyXaxkmGTtt7CmToHN2uN3Jj7/wi3xUaX+etPvl2UBDfpGTmnyByEr1hT7+5Dr2beG2CPlHSW/WbQaaq/013LBhEIULTQD4tmLLS6HDkhqMRMQJgAZjBOF0Y3iqvYrsBD6xDQTIN0BU0mgfPVcR2CiECFmAYMkTzcBwBuFievL3wjuuU7wZmh0/uj0vHVTDvGsKVKAJon5+yrBi64IU0fItDmjcff4/480QH9ePTVaJmfQ2CVw="
    - secure: "or7ty+yeeQKHP5GvLTeV1U8RrKb0HW9AV3IABIEpLAx2+Ck0V+biEd33uz8BS1QycnQt9YyAV+ToSJpeR4zEFilHXEOn0gZp3414ifeAYXxGQT+vfQjH+M1tp7sHmPLh5E7eTaz5G40AkAZC4qH1ihNOk3DtUbXa0Qe9ERCgxBFvIhjyQGizd6Q4AXSR5eI+cyydTKZyZ6hVLe1kg/fL/WXNPFkjMikzRgQNjXY79HEQviIz+KQ3d1J+1o9Gn2RpXuOJvbSKx1kdIiib239jwRGcpXpg/FHx088nPj4A53UjnAAUUKU0bKwCWqqK2D9vPDvaT9UU4DY0J70tXM/s5OeXgHBXTwAy3vUY+l7BQx1Xo1lyi1a6C3fDclnU/nZanek7yPWnH5UIrrUvgInwFxlqVouS35BxnWWUcHxwSn3ty2xIUAtSTF1BWOugJzoD6aq+c3CK/YqFfs/nJkwDvgSsD4WZn9qhFHrLW1JfzWTmG0Gw3zIONSb2+aMUeIrVxXqoR+UFfoDi5WYgGXRceGIx9f18ge/ygsEFbvPJocDQrbIdegqv7+BWYTGg7vwxrvINX+th+EIJgFNRVwerhrAIhrkrt/0gdlWIJfgCTtCQoJ/zKdTqE23BkM+ACOjZM1T0dfeob0X5lr4zpKQsofPN+6kKUiRvhjL3zuDo03o="
    - secure: "Zp/bj991aLmuQ3x5CXmWgNrocAca+gXrRuYf3xszPoqhHL2ebzQdN2S/rU6h8yhkk5tj7N1D5j+sTp2w3gryqAiGotOwRkw8XBLmCt32pzzb12dXtIBBfyrI03EIoKUgbNbA2SJVbVYqKdS5x+NRCbr0cCKpV0U6tfLIejsR0L/eJ4AqHAw+KeYHsU7dZR0FWZOYe4TYFE/qI8D+0EJMZHtMG+iZILApYoAgxm5wPgQk+kI+nQVYmOZL15cZ8pLSLSoMSCg56HZpZWQjnlc7rm262/w8JH7GQqc0myzLdakvM8QaJ8i2uBW0egSDfp1Dn4X4I0kjXydoTE99TF5E6d9ScJ966BTfCU980iqvZm2eNnLsEk4JB+UafbMaXbA1n/uYBq0N7BvdnuUGKvxlb5bXSxHDIygOkOmDpbRRjTwMJrygN3Ce4r0wkvL05pQJQu36o2J6dvjdFIaZqtXeLPMN352z+6i+sUR9XHUy05MdD4PmqQee4KFq7zwGYouYQJB35/iNujjIHVB6tR+jwASWxJxNadAuf47e4UrpGFgIhG52/OGJ+Wkmjmn2SyEtAoXWUrPs2HlF5zjesMSToUnLt2fY6jnVURwFJvq+/CcFxVlMx+jlzZbHdT2CAIb9fwdBRNmNY6ncEMqQAfbJnDohDaeTfbkNYazFe5d4T2w="


# Construct the job matrix of OS and Python versions
# Note that this cannot be done with the usual matrix as macOS and Windows do not support the "python" language option
jobs:
  fast_finish: true # Allow a single failing job to terminate other parallel jobs
  include:
    - name: "Python 3.6 on Xenial Linux"
      python: 3.6            # this works for Linux but is ignored on macOS or Windows
      env: OSBADGE=linux
    - name: "Python 3.7 on Xenial Linux"
      python: 3.7            # this works for Linux but is ignored on macOS or Windows
      env: OSBADGE=linux
    - name: "Python 3.8 on Xenial Linux"
      python: 3.8            # this works for Linux but is ignored on macOS or Windows
      env: OSBADGE=linux
    - name: "Python 3.7 on macOS"
      os: osx
      env: OSBADGE=osx
      language: generic      # 'language: python' causes an error on Travis CI macOS
    - name: "Python 3.8 on Windows"
      os: windows
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH OSBADGE=windows
      language: shell        # 'language: python' causes an error on Travis CI Windows
      before_install:
      - choco install python --version 3.8.0
      - pip3 install poetry  # note that we do not upgrade pip as this hits permissions issues


# Install poetry with pip
# All three OSes agree about 'pip3' whereas 'python' can be 2.7 or 3.x
before_install:
- pip3 install --upgrade pip
- pip3 install poetry


# Use poetry to install dependencies
install:
- poetry install


# Define job stages
script:
# Linting
- poetry run black */
- poetry run flake8 */
- poetry run pylint */
# Testing
- poetry run coverage run --source=octopusapi -m pytest tests


# Upload coverage status
after_success:
- coveralls
